# Generated by Django 3.0.8 on 2020-07-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200717_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('Richman', 'Richman'), ('Infinity', 'Infinity'), ('easy', 'easy')], max_length=20, null=True)),
                ('size', models.CharField(blank=True, choices=[('L', 'Large'), ('XL', 'Extra Large'), ('M', 'Median'), ('SM', 'Small')], max_length=255, null=True)),
                ('format', models.CharField(blank=True, choices=[('T_Shirt', 'T-Shirt'), ('Pant', 'Pant'), ('Shirt', 'shirt')], max_length=10, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
